---
abstract: 'WSDL version 1.1'
author:
  - 'Mark Overmeer'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Compile-WSDL11
no_index:
  directory:
    - t
    - inc
requires:
  Log::Report: 1.00
  Test::More: 0.54
  XML::Compile: 1.37
  XML::Compile::Cache: 0.995
  XML::Compile::SOAP11: 3.00
version: 3.00
